### ISSUE TITLE
NNG Speedcam patching

### ISSUE THREAD

**Issue by GekoCH** [diorcety/mazda3#1]
When using the command:
python nng_patcher.py -o jci-linux_imx6_volans-release.patched jci-linux_imx6_volans-release.orig

I get an error:
File "nng_patcher.py", line 55 print "SD Card ID: %s" % (payload.printCardID())
SyntaxError: invalid syntax

the 2nd " is marked as a probem, but why?

**Comment by diorcety** [comment]
You use python 3. I added in the last commit the support of python 3

**Comment by GekoCH** [comment]
yes python34 but now I get an other error, sorry:
Traceback (most recent call last):
  File "nng_patcher.py", line 18, in <module>
    from patcher import Patch, Patches, hashfile, input
ImportError: No module named 'patcher'

**Comment by diorcety** [comment]
I did an update. Can you try again

**Comment by GekoCH** [comment]
same error... same line...

**Comment by diorcety** [comment]
can you give me the exact line of your command, and the commit number?

**Comment by GekoCH** [comment]
This is the error I get:

C:\cygwin64\home\GEKO\SPD Cameras>python nng_patcher.py -o jci-linux_imx6_volans-release.patched jci-linux_imx6_volans-release.orig
Traceback (most recent call last):
  File "nng_patcher.py", line 18, in <module>
    from patcher import Patch, Patches, hashfile, input
ImportError: No module named 'patcher'

and in the "nng_patcher.py" file this corespons to this line here: "from patcher import Patch, Patches, hashfile, input"

**Comment by diorcety** [comment]
Warning .. you need all the git repository https://github.com/diorcety/mazda3/blob/master/patcher.py is needed by both tools. I haven't find a easy to have such feature (no installation, easily usable) than using relative directory according nng_patcher.py

**Comment by GekoCH** [comment]
ahhh now it works, sorry my fault!!!!

**Comment by diorcety** [comment]
No problem :)
