### ISSUE TITLE
Patch for 59.00.441A-NA version

### ISSUE THREAD

**Issue by fruizcir** [diorcety/mazda3#11]
Hi

I have problems after use nng_patcher.
Traceback (most recent call last):
  File "C:\Users\fruizcir\Documents\Fruizcir\Personal\Mazda3\NavegacionMazda\nng\nng_patcher.py", line 108, in <module>
    patches['F5F4C6DB313C480FE8ACD17B3B70DF8DC8B85652AC938AAF9BD1A95C51575C04'] =
TypeError: __init__() takes exactly 3 arguments (2 given)

I can read the CID value of SD Card: 035344535330384780E94F452500FC00
I added the jci-linux-imx6_volans_release  original of 59.00.441A-NA(Only you need remove extention .txt)
[jci-linux_imx6_volans-release.txt](https://github.com/diorcety/mazda3/files/610111/jci-linux_imx6_volans-release.txt)

**Comment by fruizcir** [comment]
Hi Dicerty,
I added the NNG file  to 59.00.441A-NA, the NNG value in previous comment is not correct, the following is correct.

C:\Users\fruizcir\Documents\Fruizcir\Personal\Mazda3\ParcherOriginal\mazda3-0.1\nng>nng_patcher.py -o jci-linux_imx6_volans-release.patched jci-linux_imx6_volans-release
Analyzing NNG file: jci-linux_imx6_volans-release
Traceback (most recent call last):
  File "C:\Users\fruizcir\Documents\Fruizcir\Personal\Mazda3\ParcherOriginal\mazda3-0.1\nng\nng_patcher.py", line 139, in <module>
    main(sys.argv)
  File "C:\Users\fruizcir\Documents\Fruizcir\Personal\Mazda3\ParcherOriginal\mazda3-0.1\nng\nng_patcher.py", line 113, in main
    raise ValueError("NNG file version not found (%s)." %(hash))
ValueError: NNG file version not found (2B2D35A968E83E978582890655C9D77A829E34937C7BAF7875211B453D137D59).

**Comment by diorcety** [comment]
The patch for this version is not available, that all.

**Comment by fruizcir** [comment]
Hi diorcety,

Can you help with this patch for 59.00.441A-NA?

**Comment by diorcety** [comment]
I will try, but not now

**Comment by fruizcir** [comment]
Ok, thanks for your help.....and waiting for the new patch.
Your work is very...very good, congratulations.

**Comment by diorcety** [comment]
Done

**Comment by fruizcir** [comment]
Hi Doircety,

I Appreciate your help....thanks....
Excellent work....

**Comment by diorcety** [comment]
no problem
