### ISSUE TITLE
Patch for 58.00.250

### ISSUE THREAD

**Issue by pagirard** [diorcety/mazda3#12]
Bonjour Yann,

Very impressed by the work done on this patcher. Seems like adding a new version involves analyzing the binary - do you have a documentation around that ? I'd love to understand better and perhaps help.

I tried to patch my NNG this weekend and for the file version not found. 
The CMU version is 58.00.250 N
the NGG is here
https://www.dropbox.com/s/x0xl7r4c2zb2mtf/jci-linux_imx6_volans-release.bak?dl=0

Any help appreciated - have a great day

**Comment by diorcety** [comment]
Done

**Comment by pagirard** [comment]
Wonderful - will try right away, many many many thanks Yann !


Happy holidays !

Pierre
