### ISSUE TITLE
Version 56.00.230_4A_N not working

### ISSUE THREAD

**Issue by TigerHuang** [diorcety/mazda3#2]
Hi, I found a new nng file from Taiwan's New Mazda 3
the version is 56.00.230 4A N
Here is the file：
https://mega.nz/#!ow9xDJKZ!hGjz3bjUG06ccHW81IYqWe54IxCSzFKzYtiChpXFkK8
Thanks for your helping : P

**Comment by diorcety** [comment]
Fixed in 2f2e35775881f9647b580e7863af77f9283cbd05
