### ISSUE TITLE
Not really an issue, but more a feature request: Importing a route/itinery

### ISSUE THREAD

**Issue by Kees-V** [diorcety/mazda3#3]
I am currently waiting for delivery of my new Mazda and diving into the possibilities of the onboard entertainment and navigation system. 
Currently I plan long road trips with Garmin Basecamp and then load the route on my Garmin navigation device.
- If I read the Mazda navigation manual correctly it is possible to define a route with several stops.
- In the software image of the entertainment and navigation system there is a folder "demo_routes" that contains several route files (route001.dat to route018.dat).

Do you see possibilities to externally define routes (e.g. on a PC) and load them into the Mazda navigation device?

**Comment by diorcety** [comment]
Certainly possible. You have to look for solution about IGO (the mazda navigation system is IGO). With the sign patch it should be possible

**Comment by Kees-V** [comment]
That's what I hope for.
One issue will be to find out how to create a compatible route file. 
Probably this could be done by creating a route via the user interface using X,Y route points and then analyzing how and where the route will be stored. Based on analysis a route could be created offline on a computer.
The second issue would be to create a script to load routes that were created offline.

**Comment by Kees-V** [comment]
According to [http://forum.routeconverter.com/thread-1035-post-7500.html#pid7500](url) importing a route on a Igo PRIMO should be possible by copying a KML file into the directory: /primo/content/userdata/route/
Will this also work on the Mazda navigation system?

**Comment by diorcety** [comment]
you may try :)

**Comment by Kees-V** [comment]
...in a few weeks :-)
