### ISSUE TITLE
NNG CID Patching

### ISSUE THREAD

**Issue by madushan1987** [diorcety/mazda3#4]
Hi,

First of all let me thank you for the great work you've done.

Now when I run the python script using the following command

`python nng_patcher.py -o jci-linux_imx6_volans-release.patched jci-linux_imx6_volans-release.orig`

I get the following error

`Analyzing NNG file: jci-linux_imx6_volans-release.orig
Traceback (most recent call last):
  File "nng_patcher.py", line 138, in <module>
    main(sys.argv)
  File "nng_patcher.py", line 112, in main
    raise ValueError("NNG file version not found (%s)." %(hash))
ValueError: NNG file version not found (8880864EE4AA6E0BAF852DFF9E2E1475640372602CDB20A816725E36F8221C2E).
`

Also I ran another tool JCI_NNG Tool v1.70 developed by Modfreakz,
It looks like he's using your python script as well, but in his tool cmd line version of the tool i got the following error

`The payload is bigger than the patch size`

Which I see it an error message from your script, so I thought that he's using your script as well,

Anyway how do I solve this issue ?

BTW this is for a mazda cmu v51

Thank you so much

**Comment by diorcety** [comment]
Hi,
This message (from my script) means that jour nng version is not handled yet. This is not an really an error just a lack of support of your  version.
Please sens me a link to your  file + the version number, i will try to add it during the coming week.
Regards

**Comment by madushan1987** [comment]
Great, Thanks

This is the link to the data.zip file and the jci-linux_imx6_volans-release.orig
https://dl.dropboxusercontent.com/u/32185272/test/test.rar

Version Number is
MZD150_51.00.000

**Comment by diorcety** [comment]
Fixed in cba0fe7f9a5a185d81679c4faa88cfad7620b148
