### ISSUE TITLE
Missing patch info for 55.00.760A

### ISSUE THREAD

**Issue by enmand** [diorcety/mazda3#5]
The patch information for 55.00.760A seems to be missing:

```
Analyzing NNG file: jci-linux_imx6_volans-release.orig
Traceback (most recent call last):
  File "nng_patcher.py", line 137, in <module>
    main(sys.argv)
  File "nng_patcher.py", line 111, in main
    raise ValueError("NNG file version not found (%s)." %(hash))
ValueError: NNG file version not found (53A3F16214EEA44C010889A78C0DCCC0EE4D330692515ACC1590E9ABAE753286).
```

Here is the nng:
https://www.dropbox.com/s/crzjw3365gcjf9i/jci-linux_imx6_volans-release.orig?dl=0

**Comment by redline0721** [comment]
Good day to you all, and thank you for all the excellent work here.  I am also having the same issue when attempting to patch 55.00.760A.  the version is not supported.

**Comment by fruizcir** [comment]
Hi all,
I have a question.....what is the procedure to obtain the CIDpatch and SingPatch?
I can help with it, I have de CID of 55.00.760A but I need the other 2 arguments...
Regards.
Fruizcir

**Comment by diorcety** [comment]
By reversing the binaries

**Comment by knt36** [comment]
I am having the same problem. Has anyone solved this?
I never did anything like this before but it seems like I have to add a patch support of some sort like this:
patches['12972815B4F98745383A4B7E6890C85CCF70CB6FF26991407D58AD4E8D395A97'] = Patches("31.00.100", [CIDPatch(0xA4C0, 0xA564)])

But how do you obtain those values and what are they?

**Comment by knt36** [comment]
This isn't a real solution, I would still like to know how to generate those values but if you patch the file with this it should work.

https://github.com/Siutsch/AIO---All-in-one-tweaks/tree/master/choose/tools/JCI_NNG_Tool

**Comment by fruizcir** [comment]
The JCI_NNG_TOOL not works!!!.
I want understand what is the process that you used to patch the jci-linux_imx6_volans-release and I can help with it.

**Comment by knt36** [comment]
The GPS does work with JCI_NNG_TOOL. I think you may be doing something wrong.

**Comment by diorcety** [comment]
I made the patch. I will commit soon. Here the patched file: http://dl.free.fr/mbhQFqsHJ

**Comment by fruizcir** [comment]
Thanks diorcety, excellent work .

**Comment by diorcety** [comment]
Is it working?
